# ??????? ?? ?????????
browser=chrome

#Yandex
yandex.driver.path=D:\Yandex_WebDriver\yandexdriver-25.4.0.1973-win64\yandexdriver.exe
yandex.browser.path=C:\Users\Tony\AppData\Local\Yandex\YandexBrowser\Application\browser.exe